# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-30 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='profile',
#            name='panel_active_teampc',
#            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.TeamParticipatesChallenge'),
#        ),
#        migrations.AddField(
#            model_name='profile',
#            name='user',
#            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
#        ),
        migrations.AlterUniqueTogether(
            name='userparticipatesonteam',
            unique_together=set([('team', 'user')]),
        ),
    ]
