# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-31 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190130_2155'),
        ('accounts', '0002_auto_20190130_2244'),
    ]

    operations = [
    ]
