# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-09 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20190131_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('txt', models.CharField(blank=True, max_length=4000, null=True)),
                ('html', models.CharField(blank=True, max_length=4000, null=True)),
                ('from_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
