# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-09 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='txt',
        ),
    ]
