# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-25 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_mail_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='City\u200c'),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[('Bachelor', 'bachelor'), ('Master', 'master'), ('PhD', 'phd')], max_length=50, null=True, verbose_name='Degree\u200c'),
        ),
        migrations.AddField(
            model_name='profile',
            name='entrance_year',
            field=models.IntegerField(null=True, verbose_name='Entrance Year\u200c'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Full Name EN\u200c'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name_fa',
            field=models.CharField(max_length=50, null=True, verbose_name='Full Name FA\u200c'),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=100, null=True, verbose_name='Major\u200c'),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(max_length=20, null=True, verbose_name='Student ID\u200c'),
        ),
        migrations.AddField(
            model_name='profile',
            name='t_shirt_size',
            field=models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('small', 'small')], max_length=50, null=True, verbose_name='T-Shirt Size\u200c'),
        ),
    ]
