# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190225_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='on_site_info_filled',
            field=models.NullBooleanField(default=False),
        ),
    ]
