# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-25 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_on_site_info_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='on_site_info_filled',
            field=models.BooleanField(default=False),
        ),
    ]
