# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-08 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='team',
            field=models.CharField(default='', max_length=128),
        ),
    ]
