# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-23 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.MultipleChoiceQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleAnswerQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Question')),
            ],
            bases=('game.question',),
        ),
        migrations.CreateModel(
            name='RangeAcceptQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Question')),
                ('min_range', models.FloatField()),
                ('max_range', models.FloatField()),
            ],
            bases=('game.question',),
        ),
        migrations.AddField(
            model_name='competition',
            name='trial_instruction',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='score',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
