# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-30 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadquestion',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
