# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='trial_time',
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
