# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-29 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
