# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190126_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='game.TeamParticipatesChallenge'),
        ),
    ]
