# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 18:29
from __future__ import unicode_literals

import apps.game.models.competition
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180104_1741'),
    ]

    operations = [
    ]
