# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-29 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190130_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrialSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trialSubmissions', to='game.TeamParticipatesChallenge')),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='score',
            new_name='max_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='value',
        ),
        migrations.AddField(
            model_name='questionsubmission',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Question'),
        ),
        migrations.AddField(
            model_name='questionsubmission',
            name='trialSubmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionSubmissions', to='game.TrialSubmission'),
        ),
    ]
