# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-30 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_fileuploadquestion_is_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadquestion',
            name='answer_file',
            field=models.FileField(null=True, upload_to=models.CharField(max_length=200)),
        ),
    ]
