# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-29 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_question_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='choice4',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.MultipleChoiceQuestion'),
        ),
    ]
