# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-29 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190130_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialsubmission',
            name='trial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Trial'),
        ),
    ]
