# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 21:51
from __future__ import unicode_literals

import apps.game.models.competition
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180118_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamparticipateschallenge',
            options={'verbose_name_plural': 'Team Participates In Challenges'},
        ),
    ]
