# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_trialsubmission_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsubmission',
            name='value',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
