# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-29 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190129_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='level',
            field=models.CharField(choices=[('difficult', 'difficult'), ('medium', 'medium'), ('easy', 'easy')], default='easy', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, choices=[('difficult', 'difficult'), ('medium', 'medium'), ('easy', 'easy')], max_length=200, null=True),
        ),
    ]
