# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 21:51
from __future__ import unicode_literals

import apps.game.models.competition
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180118_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamparticipateschallenge',
            options={'verbose_name_plural': 'Team Participates In Challenges'},
        ),
        migrations.AddField(
            model_name='teamsubmission',
            name='infra_compile_token',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teamsubmission',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('compiling', 'Compiling'), ('compiled', 'Compiled')], default='uploading', max_length=128),
        ),
        migrations.AlterField(
            model_name='teamsubmission',
            name='language',
            field=models.CharField(choices=[('c++', 'C++'), ('java', 'Java'), ('python2', 'Python 2'), ('python3', 'Python 3')], default='java', max_length=128),
        ),
    ]
