# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-30 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_questionsubmission_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsubmission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Question'),
        ),
    ]
