# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20180126_0015'),
    ]

    operations = [
    ]
