# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_map_token'),
    ]

    operations = [
    ]
