# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-03 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20180203_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(choices=[('elim', 'Elimination'), ('double', 'Double Elimination'), ('league', 'League'), ('friendly', 'Friendly')], max_length=128),
        ),
    ]
