# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_remove_singlematch_done'),
    ]

    operations = [
    ]
