# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-20 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20180214_0142'),
    ]

    operations = [
    ]
