# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-22 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20180306_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stmt', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='map',
            name='competitions',
        ),
        migrations.RemoveField(
            model_name='match',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='match',
            name='part1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='part2',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='singlematch',
            name='map',
        ),
        migrations.RemoveField(
            model_name='singlematch',
            name='match',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='type',
        ),
        migrations.AddField(
            model_name='competition',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='trial_time',
            field=models.IntegerField(default=24),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Question')),
                ('choice1', models.CharField(max_length=50)),
                ('choice2', models.CharField(max_length=50)),
            ],
            bases=('game.question',),
        ),
        migrations.CreateModel(
            name='ShortAnswerQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Question')),
            ],
            bases=('game.question',),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='SingleMatch',
        ),
        migrations.AddField(
            model_name='trial',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Competition'),
        ),
        migrations.AddField(
            model_name='trial',
            name='questions',
            field=models.ManyToManyField(blank=True, to='game.Question'),
        ),
        migrations.AddField(
            model_name='trial',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.TeamParticipatesChallenge'),
        ),
    ]
