# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-24 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20190124_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='current_trial_id',
            field=models.IntegerField(default=0),
        ),
    ]
