# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-31 12:34
from __future__ import unicode_literals

import apps.game.models.competition
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20190131_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.game.models.competition.user_directory_path),
        ),
        migrations.AddField(
            model_name='competition',
            name='dataset_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trial',
            name='dataset_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.MultipleChoiceQuestion'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='model_name',
            field=models.CharField(choices=[('Question', 'Question'), ('IntervalQuestion', 'IntervalQuestion'), ('FileUploadQuestion', 'FileUploadQuestion'), ('MultipleAnswerQuestion', 'MultipleAnswerQuestion'), ('MultipleChoiceQuestion', 'MultipleChoiceQuestion')], max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='ui_type',
            field=models.CharField(blank=True, choices=[('text_number', 'text_number'), ('text_string', 'text_string'), ('choices', 'choices'), ('multiple', 'multiple'), ('file', 'file'), ('image_choices', 'image_choices')], max_length=200),
        ),
    ]
