# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-31 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_auto_20190131_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='imaged',
            field=models.BooleanField(default=False),
        ),
    ]
