# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-01 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_multiplechoicequestion_imaged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ('-pk',)},
        ),
    ]
