# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-01 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_multiplechoicequestion_imaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialsubmission',
            name='score',
            field=models.FloatField(default=-2),
        ),
    ]
