# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-01 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_auto_20190201_1735'),
        ('game', '0029_auto_20190201_1652'),
    ]

    operations = [
    ]
