# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-01 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_merge_20190201_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='group_id',
        ),
    ]
