# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-01 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_remove_question_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='doc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
