# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-02 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_auto_20190202_0056'),
        ('game', '0030_merge_20190201_1954'),
    ]

    operations = [
    ]
