# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-02 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_merge_20190202_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsubmission',
            old_name='trialSubmission',
            new_name='trial_submission',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('multiple_choice', 'multiple_choice'), ('single_answer', 'single_answer'), ('multiple_answer', 'multiple_answer'), ('single_sufficient_answer', 'single_sufficient_answer'), ('single_number', 'single_number'), ('interval_number', 'interval_number'), ('file_upload', 'file_upload')], max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='ui_type',
            field=models.CharField(blank=True, choices=[('text_number', 'text_number'), ('text_string', 'text_string'), ('choices', 'choices'), ('multiple', 'multiple'), ('file', 'file'), ('image_choices', 'image_choices')], max_length=200),
        ),
    ]
