# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-02 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_auto_20190202_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialsubmission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_submissions', to='game.TeamParticipatesChallenge'),
        ),
    ]
