# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-09 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_auto_20190202_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='trial_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
