# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_trial_trial_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='trial_per_day',
        ),
        migrations.AddField(
            model_name='competition',
            name='trial_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
