# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-09 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_trialsubmission_is_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialsubmission',
            name='is_final',
        ),
        migrations.AddField(
            model_name='trial',
            name='is_final',
            field=models.NullBooleanField(),
        ),
    ]
