# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_auto_20190209_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='final',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='fileuploadquestion',
            name='score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('multiple_choice', 'multiple_choice'), ('single_answer', 'single_answer'), ('multiple_answer', 'multiple_answer'), ('single_sufficient_answer', 'single_sufficient_answer'), ('single_number', 'single_number'), ('interval_number', 'interval_number'), ('file_upload', 'file_upload'), ('triple_cat_file_upload', 'triple_cat_file_upload')], max_length=200),
        ),
    ]
