# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_auto_20190209_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeUploadQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Question')),
                ('upload_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('game.question',),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('multiple_choice', 'multiple_choice'), ('single_answer', 'single_answer'), ('multiple_answer', 'multiple_answer'), ('single_sufficient_answer', 'single_sufficient_answer'), ('single_number', 'single_number'), ('interval_number', 'interval_number'), ('file_upload', 'file_upload'), ('triple_cat_file_upload', 'triple_cat_file_upload'), ('code_upload', 'code_upload')], max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='ui_type',
            field=models.CharField(blank=True, choices=[('text_number', 'text_number'), ('text_string', 'text_string'), ('choices', 'choices'), ('multiple', 'multiple'), ('file', 'file'), ('image_choices', 'image_choices'), ('code', 'code')], max_length=200),
        ),
    ]
