# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-25 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_auto_20190211_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamparticipateschallenge',
            name='payment_time_remained',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
