# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-26 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_auto_20190226_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='invited_to_ranking',
            field=models.IntegerField(default=-1),
        ),
    ]
