# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-27 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0049_auto_20190227_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamparticipateschallenge',
            name='payment_last_time_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
