# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-03 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0051_auto_20190303_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUploadQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Question')),
                ('upload_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('game.question',),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('multiple_choice', 'multiple_choice'), ('single_answer', 'single_answer'), ('multiple_answer', 'multiple_answer'), ('single_sufficient_answer', 'single_sufficient_answer'), ('single_number', 'single_number'), ('interval_number', 'interval_number'), ('file_upload', 'file_upload'), ('triple_cat_file_upload', 'triple_cat_file_upload'), ('code_upload', 'code_upload'), ('onsite_code_upload', 'onsite_code_upload'), ('onsite_file_upload', 'onsite_file_upload'), ('report_upload', 'report_upload')], max_length=200),
        ),
    ]
