# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-04 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0052_auto_20190303_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='trial_submit_type',
            field=models.CharField(blank=True, choices=[('MEAN', 'MEAN'), ('FINAL', 'FINAL')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('multiple_choice', 'multiple_choice'), ('single_answer', 'single_answer'), ('multiple_answer', 'multiple_answer'), ('single_sufficient_answer', 'single_sufficient_answer'), ('single_number', 'single_number'), ('interval_number', 'interval_number'), ('file_upload', 'file_upload'), ('triple_cat_file_upload', 'triple_cat_file_upload'), ('boolean_file_upload', 'boolean_file_upload'), ('code_upload', 'code_upload'), ('onsite_code_upload', 'onsite_code_upload'), ('onsite_file_upload', 'onsite_file_upload'), ('report_upload', 'report_upload')], max_length=200),
        ),
    ]
