# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-05 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0054_challenge_onsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=600)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='game.TeamParticipatesChallenge')),
            ],
        ),
    ]
