# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-05 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0055_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information',
            new_name='Notification',
        ),
    ]
