# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0056_auto_20190305_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
