# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-06 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0057_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(blank=True, choices=[('online_phase_1', 'online_phase_1'), ('online_phase_2', 'online_phase_2'), ('onsite_day_1', 'onsite_day_1'), ('onsite_day_1_2', 'onsite_day_1_2'), ('onsite_day_2', 'onsite_day_2')], max_length=200, null=True),
        ),
    ]
